---
- name: Update package cache
  package:
    update_cache: yes

- name: Upgrade installed packages
  package:
    name: "*"
    state: latest

- name: Install common packages
  package:
    name:
      - curl
      - unzip
      - wget
      - git
      - tar
      - vim
    state: present