---
- name: Download AWS CLI installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Extract AWS CLI installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI
  command: /tmp/aws/install --update

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_version

- name: Show AWS CLI version
  debug:
    var: aws_version.stdout